M48
; DRILL file {KiCad 7.0.10} date Sun Feb 25 15:08:56 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-25T15:08:56-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.0369Y-1.6769
X3.0369Y-4.0391
X4.6904Y-3.2517
X4.8085Y-2.3068
M30
