M48
; DRILL file {KiCad 7.0.10} date Tue Mar 26 13:41:40 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-26T13:41:40-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.3268Y-2.874
X3.3268Y-5.0394
X6.2795Y-2.874
X6.2795Y-5.0394
M30
